-- Oracle schema for SevaBite
-- Run this using SQL*Plus as the user/schema you want to store the tables in.

-- Donations table (idempotent: skips creation if it already exists)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE donations (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR2(120) NOT NULL,
      email VARCHAR2(190) NOT NULL,
      amount NUMBER(10,2) NOT NULL,
      message CLOB,
      timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    -- ORA-00955: name is already used by an existing object
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- Contacts table (idempotent)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE contacts (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR2(120) NOT NULL,
      email VARCHAR2(190) NOT NULL,
      message CLOB NOT NULL,
      timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
